# -*- coding: utf-8 -*-
"""python_typing_zad_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_1eIfyL7svRcorM-rdDMav0liADOOlQ
"""

#python_typing
# zad.1

def pelne_imie():
    name = str(input("Podaj imię: "))
    surname = str(input("Podaj nazwisko: "))
    full_name = f"{name} {surname}"
    return full_name

full_name = pelne_imie()

print(f"Twoje imię i nazwisko to: {full_name}")