# -*- coding: utf-8 -*-
"""python_typing_zad_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7esP3dbK5m8xcqOW96d-pekWrefAydD
"""

# python_typing
# zad.2

a = int(input("Wpisz 1 liczbe: "))
b = int(input("Wpisz 2 liczbe: "))
c = a * b


print("wynik mnożenia tych liczb to: ", c)