# -*- coding: utf-8 -*-
"""python_typing_zad_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C_EAYayliJWPMUpjMqFtI3AEkbTu1QBf
"""

# python_typing
# zad 3
def sprawdz_parzystosc(liczba):
    return liczba % 2 == 0

# Wczytanie liczby od użytkownika
x = int(input("Wpisz liczbę: "))

# Przykładowe użycie funkcji
wynik = sprawdz_parzystosc(x)

# Wyświetlenie odpowiedniego komunikatu na podstawie wyniku
if wynik:
    print("Liczba parzysta")
else:
    print("Liczba nieparzysta")