# -*- coding: utf-8 -*-
"""zad3oop

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RL8D2n4r0I6u7xPyGQSZ8r4rOjKxzgot
"""

#zad 3 oop

class property:
    def __init__(self, area, rooms, price, address):
        self.area = area
        self.rooms = rooms
        self.price = price
        self.address = address

    def __str__(self):
        return f"property: {self.area} sq. meters, {self.rooms} rooms\n" \
               f"price: ${self.price}\nAddress: {self.address}"


class house(property):
    def __init__(self, area, rooms, price, address, plot):
        super().__init__(area, rooms, price, address)
        self.plot = plot

    def __str__(self):
        return f"house: {self.area} sq. meters, {self.rooms} rooms\n" \
               f"price: ${self.price}\nAddress: {self.address}\n" \
               f"plot: {self.plot} sq. meters"


class flat(property):
    def __init__(self, area, rooms, price, address, floor):
        super().__init__(area, rooms, price, address)
        self.floor = floor

    def __str__(self):
        return f"flat: {self.area} sq. meters, {self.rooms} rooms\n" \
               f"price: ${self.price}\nAddress: {self.address}\n" \
               f"floor: {self.floor}"


house = house(area=150, rooms=5, price=200000, address="123 Main Street",
              plot=500)


flat = flat(area=80, rooms=3, price=120000, address="456 Oak Avenue", floor=2)


print("house:")
print(house)

print("\nflat:")
print(flat)