# -*- coding: utf-8 -*-
"""python_typing_zad_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AcR52kxY57kf8JdHdumXjAVJZ6A1eb2G
"""

# python_typing
# zad 5

def sprawdz_obecnosc_wartosci(lista, wartosc):
    return wartosc in lista


# Inicjalizacja pustej listy
moja_lista = []

# Pętla do wprowadzania wartości
while True:
    # Wprowadzanie wartości od użytkownika
    wprowadzona_wartosc = input("Wpisz wartość (wpisz 'k' aby zakończyć): ")

    # Sprawdzenie warunku zakończenia wprowadzania
    if wprowadzona_wartosc.lower() == 'k':
        break

    # Dodanie wartości do listy (przy założeniu, że wprowadzona wartość to liczba)
    try:
        wartosc = int(wprowadzona_wartosc)
        moja_lista.append(wartosc)
    except ValueError:
        print("Wprowadź poprawną liczbę!")

# Wyświetlenie uzyskanej listy
print("Twoja lista:", moja_lista)

x = int(input("Wpisz liczbę do sprawdzenia: "))

wynik = sprawdz_obecnosc_wartosci(moja_lista, x)

# Wyświetlenie wyniku
print(wynik)